version: '3'
services:
  cf-proformas-storage-trigger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${DOCKER_SERVICE_NAME}
    environment:
      PYTHONUNBUFFERED: 1
    env_file: .env
    command: "functions-framework --target=init --debug"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    ports:
      - "${DOCKER_PORT}:8080"
    networks:
      - backend
networks:
  backend:
      external: true
      name: ${DOCKER_NETWORK}